export const courses = [
  {
    id: "lotus",
    slug: "lotus",
    title: "荷塘月色",
    author: "朱自清",
    stage: "初中语文阅读",
    gradeLabel: "初二",
    genre: "抒情散文",
    route: "/index.html",
    sourceType: "full-flow",
    status: "published",
    summary: "从月下荷塘的景物描写进入作者内心波动，重点训练意境还原、语言赏析与情感曲线理解。",
    subtitle: "情景交融与意境赏析",
    tags: ["意境还原", "语言赏析", "情感曲线", "仿写训练"],
    entryLabel: "当前演示进度",
    entryValue: "完整学习流程已接入"
  },
  {
    id: "back",
    slug: "back",
    title: "背影",
    author: "朱自清",
    stage: "初中语文阅读",
    gradeLabel: "初一",
    genre: "亲情散文",
    route: "/course-content.html?course=back",
    sourceType: "content-page",
    status: "published",
    summary: "围绕买橘子的经典场景，训练细节描写识别、情感转折理解和叙事视角感受。",
    subtitle: "细节描写与亲情表达",
    tags: ["细节描写", "父子亲情", "叙事散文"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "baicao",
    slug: "baicao",
    title: "从百草园到三味书屋",
    author: "鲁迅",
    stage: "初中语文阅读",
    gradeLabel: "初一",
    genre: "回忆散文",
    route: "/course-content.html?course=baicao",
    sourceType: "content-page",
    status: "published",
    summary: "通过园中乐趣与书塾生活的对照，理解童年视角、场景转换和叙述节奏。",
    subtitle: "场景转换与童趣体验",
    tags: ["回忆散文", "对比阅读", "童年视角"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "wisteria",
    slug: "wisteria",
    title: "紫藤萝瀑布",
    author: "宗璞",
    stage: "初中语文阅读",
    gradeLabel: "初一",
    genre: "抒情散文",
    route: "/course-content.html?course=wisteria",
    sourceType: "content-page",
    status: "published",
    summary: "从紫藤萝盛放的视觉描写进入生命主题，适合训练象征意义和抒情语句的深层理解。",
    subtitle: "景物象征与生命感悟",
    tags: ["托物言志", "象征", "生命主题"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "spring",
    slug: "spring",
    title: "春",
    author: "朱自清",
    stage: "初中语文阅读",
    gradeLabel: "初一",
    genre: "写景散文",
    route: "/course-content.html?course=spring",
    sourceType: "content-page",
    status: "published",
    summary: "通过春草、春花、春雨等层层展开的描写，训练景物特征提炼和语言节奏感把握。",
    subtitle: "多感官写景与节奏感",
    tags: ["写景散文", "修辞赏析", "节奏感"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "winter",
    slug: "winter",
    title: "济南的冬天",
    author: "老舍",
    stage: "初中语文阅读",
    gradeLabel: "初一",
    genre: "城市写景",
    route: "/course-content.html?course=winter",
    sourceType: "content-page",
    status: "published",
    summary: "理解作者如何用柔和而富有温度的语言写出济南冬天的可爱，训练整体感知能力。",
    subtitle: "温暖冬景与语言温度",
    tags: ["城市风景", "语言风格", "整体感知"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "walk",
    slug: "walk",
    title: "散步",
    author: "莫怀戚",
    stage: "初中语文阅读",
    gradeLabel: "初二",
    genre: "家庭主题",
    route: "/course-content.html?course=walk",
    sourceType: "content-page",
    status: "published",
    summary: "聚焦家庭成员关系和叙事细节，训练从平实语言中读出情感层次与主题意味。",
    subtitle: "责任选择与家庭温情",
    tags: ["家庭伦理", "细节解读", "主题归纳"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "opera",
    slug: "opera",
    title: "社戏",
    author: "鲁迅",
    stage: "初中语文阅读",
    gradeLabel: "初二",
    genre: "小说阅读",
    route: "/course-content.html?course=opera",
    sourceType: "content-page",
    status: "published",
    summary: "从看戏前后的活动和乡村夜景入手，训练小说情节梳理与人物感受捕捉。",
    subtitle: "童年叙事与乡土记忆",
    tags: ["小说阅读", "人物关系", "乡土叙事"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "peach",
    slug: "peach",
    title: "桃花源记",
    author: "陶渊明",
    stage: "初中语文阅读",
    gradeLabel: "初二",
    genre: "文言阅读",
    route: "/course-content.html?course=peach",
    sourceType: "content-page",
    status: "published",
    summary: "围绕发现桃源的叙事线索，训练文言翻译、结构分层和理想社会主题理解。",
    subtitle: "理想社会与文言感知",
    tags: ["文言文", "理想社会", "叙事线索"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  },
  {
    id: "tower",
    slug: "tower",
    title: "岳阳楼记",
    author: "范仲淹",
    stage: "初中语文阅读",
    gradeLabel: "初三",
    genre: "古文名篇",
    route: "/course-content.html?course=tower",
    sourceType: "content-page",
    status: "published",
    summary: "从景物描写与议论抒情的结合切入，理解家国情怀与古文表达的结构力量。",
    subtitle: "家国情怀与议论表达",
    tags: ["古文名篇", "议论抒情", "家国情怀"],
    entryLabel: "当前入口",
    entryValue: "独立课程内容页"
  }
];
